import type { HighValueFixtureEntry } from './formatter-fixtures.ts';

/** Empty GetNotificationsResponse (schema-shaped; array not null). */
export const emptyNotificationsFixture = {
  count: 0,
  current_tick: 900683,
  notifications: [] as Array<Record<string, unknown>>,
  remaining: 0,
  timestamp: 1779562779,
};

/**
 * Mixed notification poll sample: system + chat + market update + ship commission receipt.
 * Notification items include required schema fields (id, type, msg_type, timestamp, data).
 */
export const getNotificationsFixture = {
  count: 4,
  current_tick: 901337,
  notifications: [
    {
      id: 'notif-system-1',
      type: 'system',
      msg_type: 'system',
      data: { message: 'Server maintenance scheduled.' },
      timestamp: '2026-05-23T18:59:39.049Z',
    },
    {
      id: 'notif-chat-1',
      type: 'chat',
      msg_type: 'chat_message',
      data: { channel: 'local', sender: 'Ibis', content: 'Clear skies over Sol today.' },
      timestamp: '2026-05-23T19:01:02.000Z',
    },
    {
      id: 'notif-market-1',
      type: 'market',
      msg_type: 'market_update',
      data: {
        base_id: 'haven_exchange',
        base_name: 'Haven Exchange',
        tick: 901337,
        items: [
          {
            item_id: 'ore_iron',
            item_name: 'Iron Ore',
            sell_orders: [{ price_each: 12, quantity: 40, source: 'station' }],
            buy_orders: [{ price_each: 9, quantity: 25 }],
          },
        ],
      },
      timestamp: '2026-05-23T19:03:02.000Z',
    },
    {
      id: 'notif-ship-1',
      type: 'system',
      msg_type: 'ship_commission_complete',
      data: {
        tick: 901400,
        commission_id: 'commission-1',
        ship_id: 'ship-42',
        ship_class: 'prospector',
        ship_name: 'Prospector',
        base_id: 'earth_station',
        base_name: 'Earth Station',
      },
      timestamp: '2026-07-17T20:00:00.000Z',
    },
  ],
  remaining: 0,
  timestamp: 1779562982,
};

/** One schema-complete mixed observation_update poll response (v0.554 contact domains). */
export const getNotificationsObservationFixture = {
  count: 1,
  current_tick: 901500,
  notifications: [
    {
      id: 'notif-observation-1',
      type: 'observation',
      msg_type: 'observation_update',
      data: {
        active_scan: true,
        cloaked_lost: ['player-cloaked-old'],
        cloaked_resolved: [
          {
            target_id: 'player-cloaked-1',
            revealed_info: ['username', 'ship_class', 'hull', 'shield', 'cloaked'],
            cloaked: true,
            faction_id: 'smc',
            hull: 72,
            shield: 18,
            ship_class: 'scout',
            ship_name: 'Quiet Current',
            username: 'Wisp',
          },
        ],
        creatures_changed: [
          {
            creature_id: 'creature-pilot-whale-7',
            species: 'pilot_whale',
            name: 'Pilot-Whale Pod',
            role: 'grazer',
            hull: 76,
            max_hull: 120,
            in_combat: true,
            brand_faction: 'smc',
            brand_ranch: 'cloudbank-ranch',
            branded: true,
          },
        ],
        creatures_departed: ['creature-starfish-2'],
        empire_npcs_changed: [
          {
            npc_id: 'npc-patrol-7',
            name: 'Solarian Patrol',
            role: 'patrol',
            empire: 'solarian',
            in_combat: true,
            fleet_name: 'Seventh Watch',
            ship_class: 'interceptor',
            ship_name: 'Vigilant',
          },
        ],
        empire_npcs_departed: ['npc-freighter-2'],
        nearby_changed: [
          {
            clan_tag: 'SMC',
            docked: false,
            faction_id: 'smc',
            faction_tag: 'SMC',
            in_combat: false,
            offline: false,
            player_id: 'player-marlowe',
            primary_color: '#335577',
            secondary_color: '#88aacc',
            ship_class: 'prospector',
            ship_name: 'Long Survey',
            status_message: 'mapping Cloudbank',
            username: 'Marlowe',
          },
        ],
        nearby_departed: ['player-ibis'],
        pirates_changed: [
          {
            pirate_id: 'pirate-corsair-7',
            name: 'Corsair',
            tier: 'skiff',
            is_boss: false,
            status: 'hostile',
            faction: 'pirate_kael',
            faction_name: 'Admiral Kael',
            hull: 32,
            max_hull: 50,
            shield: 0,
            max_shield: 20,
          },
          {
            pirate_id: 'pirate-raider-8',
            name: 'Raider',
            tier: 'cutter',
            is_boss: false,
            status: 'damaged',
            faction: 'pirate_voss',
            faction_name: 'Captain Voss',
            hull: 12,
            max_hull: 60,
            shield: 0,
            max_shield: 15,
          },
        ],
        pirates_departed: ['pirate-raider-6'],
        poi_id: 'sol_cloudbank',
        system_changed: [
          {
            clan_tag: 'FREE',
            docked: true,
            faction_id: 'free-captains',
            faction_tag: 'FREE',
            in_combat: false,
            offline: false,
            player_id: 'player-oriole',
            primary_color: '#775533',
            secondary_color: '#ccaa88',
            ship_class: 'hauler',
            ship_name: 'Outbound',
            status_message: 'departing soon',
            username: 'Oriole',
          },
        ],
        system_departed: ['player-wren'],
        system_id: 'sol',
        tick: 901500,
        unknown_signature: true,
      },
      timestamp: '2026-05-23T19:05:02.000Z',
    },
  ],
  remaining: 0,
  timestamp: 1779563102,
};

/** Combat kill poll: player_kill, player_died, pirate private, pirate broadcast, hidden POI. */
export const getNotificationsCombatKillsFixture = {
  count: 5,
  current_tick: 901780,
  remaining: 0,
  timestamp: 1779564000,
  notifications: [
    {
      id: 'notif-player-kill-1',
      type: 'combat',
      msg_type: 'player_kill',
      timestamp: '2026-05-23T19:10:00.000Z',
      data: {
        victim: 'Marlowe',
        wreck_id: 'wreck-1',
        wreck_has_cargo: true,
        wreck_has_modules: false,
        wreck_poi_id: 'sol_asteroid_belt',
        wreck_poi_name: 'Asteroid Belt',
        wreck_system_id: 'sol',
        wreck_system_name: 'Sol',
      },
    },
    {
      id: 'notif-player-died-1',
      type: 'combat',
      msg_type: 'player_died',
      timestamp: '2026-05-23T19:10:05.000Z',
      data: {
        killer_id: 'player-raider',
        killer_name: 'Raider',
        cause: 'combat',
        respawn_base: 'earth_station',
        clone_cost: 500,
        insurance_payout: 1200,
        ship_lost: 'Dust Devil',
        wreck_id: 'wreck-2',
        wreck_poi_id: 'alfirk_gate',
        wreck_poi_name: 'Gate Alpha',
        wreck_system_id: 'alfirk',
        wreck_system_name: 'Alfirk',
        combat_log: {
          message: 'Last stand at the gate',
          attacker_ship: 'raider_frigate',
          weapons_used: { laser: 3, missile: 1 },
          total_damage: 120,
          shield_damage: 40,
          hull_damage: 80,
          combat_rounds: 4,
          death_location: 'Gate Alpha',
          death_system: 'Alfirk',
        },
      },
    },
    {
      id: 'notif-pirate-destroyed-1',
      type: 'combat',
      msg_type: 'pirate_destroyed',
      timestamp: '2026-05-23T19:10:10.000Z',
      data: {
        pirate_id: 'pirate-corsair-7',
        pirate_name: 'Corsair',
        pirate_role: 'raider',
        is_boss: false,
        credits_earned: 150,
        combat_xp: 25,
        wreck_id: 'wreck-3',
        wreck_has_cargo: true,
        wreck_has_modules: true,
        wreck_poi_id: 'sol_cloudbank',
        wreck_poi_name: 'Cloudbank',
        wreck_system_id: 'sol',
        wreck_system_name: 'Sol',
      },
    },
    {
      id: 'notif-pirate-broadcast-1',
      type: 'combat',
      msg_type: 'pirate_destroyed',
      timestamp: '2026-05-23T19:10:15.000Z',
      data: {
        pirate_name: 'Dreadnought',
        pirate_role: 'boss',
        killer: 'Marlowe',
        system_id: 'sol',
        system_name: 'Sol',
        message: 'Marlowe destroyed the Dreadnought in Sol!',
      },
    },
    {
      id: 'notif-player-kill-hidden-1',
      type: 'combat',
      msg_type: 'player_kill',
      timestamp: '2026-05-23T19:10:20.000Z',
      data: {
        victim: 'Wisp',
        wreck_id: 'wreck-hidden-1',
        wreck_system_id: 'sol',
        wreck_system_name: 'Sol',
      },
    },
  ],
};

/** Boarding capture + prize recovery poll: ship_captured plus prize_update rows. */
export const getNotificationsPrizesFixture = {
  count: 7,
  current_tick: 901810,
  remaining: 0,
  timestamp: 1779564100,
  notifications: [
    {
      id: 'notif-ship-captured-1',
      type: 'combat',
      msg_type: 'ship_captured',
      timestamp: '2026-05-23T19:12:00.000Z',
      data: {
        battle_id: 'battle-42',
        tick: 901800,
        boarding_operation_id: 'board-1',
        captor_id: 'player-1',
        captor_username: 'Marlowe',
        former_owner_id: 'pirate-1',
        former_owner_username: 'Corsair-7',
        ship_id: 'ship-skiff-1',
        ship_class: 'skiff',
      },
    },
    {
      id: 'notif-prize-stall-1',
      type: 'prize',
      msg_type: 'prize_update',
      timestamp: '2026-05-23T19:12:05.000Z',
      data: {
        prize_id: 'prize-1',
        ship_id: 'ship-recover-1',
        ship_class: 'frigate',
        ship_name: 'Captured Lark',
        status: 'in_transit',
        wait_reason: 'no_fuel',
        destination_base_id: 'earth_station',
        system_id: 'sol',
        poi_id: 'sol_cloudbank',
        message: 'Prize recovery stopped: fuel empty',
      },
    },
    {
      id: 'notif-prize-delivered-1',
      type: 'prize',
      msg_type: 'prize_update',
      timestamp: '2026-05-23T19:12:10.000Z',
      data: {
        prize_id: 'prize-1',
        ship_id: 'ship-recover-1',
        ship_class: 'frigate',
        ship_name: 'Captured Lark',
        status: 'delivered',
        destination_base_id: 'earth_station',
        message: 'Prize delivered to storage',
      },
    },
    {
      id: 'notif-prize-destroyed-1',
      type: 'prize',
      msg_type: 'prize_update',
      timestamp: '2026-05-23T19:12:15.000Z',
      data: {
        prize_id: 'prize-1',
        ship_id: 'ship-recover-1',
        ship_class: 'frigate',
        ship_name: 'Captured Lark',
        status: 'destroyed',
        wreck_id: 'wreck-9',
        system_id: 'sol',
        poi_id: 'sol_cloudbank',
        message: 'Prize hull destroyed',
      },
    },
    {
      id: 'notif-prize-available-1',
      type: 'prize',
      msg_type: 'prize_update',
      timestamp: '2026-05-23T19:12:20.000Z',
      data: {
        prize_id: 'prize-2',
        ship_id: 'ship-claim-1',
        ship_class: 'skiff',
        ship_name: 'Open Prize',
        status: 'available',
        message: 'Prize is available to claim',
      },
    },
    {
      id: 'notif-prize-expired-1',
      type: 'prize',
      msg_type: 'prize_update',
      timestamp: '2026-05-23T19:12:25.000Z',
      data: {
        prize_id: 'prize-3',
        ship_id: 'ship-expired-1',
        ship_class: 'frigate',
        ship_name: 'Timed Out',
        status: 'expired',
        wreck_id: 'wreck-expired-1',
        system_id: 'sol',
        poi_id: 'sol_cloudbank',
        message: 'Prize claim window expired',
      },
    },
    {
      id: 'notif-prize-recaptured-1',
      type: 'prize',
      msg_type: 'prize_update',
      timestamp: '2026-05-23T19:12:30.000Z',
      data: {
        prize_id: 'prize-4',
        ship_id: 'ship-recap-1',
        ship_class: 'frigate',
        ship_name: 'Lost Lark',
        status: 'recaptured',
        message: 'Prize was recaptured',
      },
    },
  ],
};

export const notificationsHighValueFixtures: Record<string, HighValueFixtureEntry> = {
  get_notifications: {
    command: 'get_notifications',
    fixture: getNotificationsFixture,
  },
  get_notifications_observation: {
    command: 'get_notifications',
    fixture: getNotificationsObservationFixture,
  },
  get_notifications_combat_kills: {
    command: 'get_notifications',
    fixture: getNotificationsCombatKillsFixture,
  },
  get_notifications_prizes: {
    command: 'get_notifications',
    fixture: getNotificationsPrizesFixture,
  },
  // Covers the GET /notifications alias command + empty poll path (shared formatter).
  notifications: {
    command: 'notifications',
    fixture: emptyNotificationsFixture,
    // GET route only documents V2Response; compare against the shared poll body schema.
    apiRoute: 'POST /api/v2/spacemolt/get_notifications',
  },
};
