import * as fs from 'node:fs';
import * as path from 'node:path';
import { generateApiRoutes, type GeneratedApiRoute, type OpenApiSpec } from '../src/openapi-metadata';

const root = path.join(import.meta.dir, '..');
const openApiPath = path.join(root, 'spacemolt-docs', 'openapi.json');
const outputPath = path.join(root, 'src', 'generated', 'api-commands.ts');

export type { GeneratedApiRoute, OpenApiSpec } from '../src/openapi-metadata';
export { generateApiRoutes as generate } from '../src/openapi-metadata';

function render(routes: Record<string, GeneratedApiRoute>): string {
  const routeHasCliMetadata = Object.values(routes).some((route) => route.cli);

  return `// Generated by scripts/generate-api-metadata.ts from spacemolt-docs/openapi.json.
// Do not edit by hand.

export interface GeneratedApiField {
  type?: string;
  enum?: string[];
  description?: string;
  positionalIndex?: number;
}

export interface GeneratedApiRoute {
  operationId?: string;
  summary?: string;
  route: {
    tool: string;
    action: string;
    method: 'GET' | 'POST';
  };
  required?: string[];
  schema?: Record<string, GeneratedApiField>;
${
  routeHasCliMetadata
    ? `  cli?: {
    command?: string;
    category?: string;
    hidden?: boolean;
  };
`
    : ''
}}

export const GENERATED_API_ROUTES: Record<string, GeneratedApiRoute> = ${JSON.stringify(routes, null, 2)};
`;
}

if (import.meta.main) {
  const spec = JSON.parse(fs.readFileSync(openApiPath, 'utf-8')) as OpenApiSpec;
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, render(generateApiRoutes(spec)));
}
