import { describe, expect, test } from 'bun:test';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import {
  type GeneratedApiRoute,
  generateApiMetadataFile,
  type OpenApiSpec,
  renderGeneratedApiRoutes,
} from './generate-api-metadata';

describe('generate-api-metadata', () => {
  test('renderGeneratedApiRoutes includes CLI metadata only when present', () => {
    const route: GeneratedApiRoute = {
      operationId: 'toolAction',
      summary: 'Tool action',
      route: { tool: 'tool', action: 'action', method: 'POST' },
      cli: { command: 'tool_action', category: 'Tools' },
    };

    const renderedWithCli = renderGeneratedApiRoutes(
      {
        'POST /api/v2/tool/action': route,
      },
      'v0.324.1',
    );
    const renderedWithoutCli = renderGeneratedApiRoutes(
      {
        'POST /api/v2/tool/action': { ...route, cli: undefined },
      },
      'v0.324.1',
    );

    expect(renderedWithCli).toContain(
      '// Generated by scripts/generate-api-metadata.ts from spacemolt-docs/openapi.json for gameserver v0.324.1.',
    );
    expect(renderedWithCli).toContain('  cli?: {');
    expect(renderedWithCli).toContain("'tool_action'");
    expect(renderedWithoutCli).not.toContain('  cli?: {');
    expect(renderedWithCli).toContain("export const GENERATED_API_GAMESERVER_VERSION = 'v0.324.1';");
  });

  test('generateApiMetadataFile writes deterministic TypeScript from a spec file', () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'spacemolt-api-metadata-'));
    try {
      const openApiPath = path.join(tempDir, 'openapi.json');
      const outputPath = path.join(tempDir, 'generated', 'api-commands.ts');
      const spec = {
        info: { 'x-gameserver-version': 'v0.324.1' },
        paths: {
          '/api/v2/spacemolt_probe/ping': {
            post: {
              operationId: 'probePing',
              summary: 'Ping probe',
              'x-state-sections': ['ship', 'cargo'],
              requestBody: {
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      required: ['id'],
                      properties: {
                        id: { type: 'string', 'x-positional-index': 0 },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      } as OpenApiSpec;

      fs.writeFileSync(openApiPath, JSON.stringify(spec));

      generateApiMetadataFile({ openApiPath, outputPath });

      const output = fs.readFileSync(outputPath, 'utf-8');
      expect(
        output,
      ).toBe(`// Generated by scripts/generate-api-metadata.ts from spacemolt-docs/openapi.json for gameserver v0.324.1.
// Do not edit by hand.

export interface GeneratedApiField {
  type?: string;
  enum?: string[];
  description?: string;
  positionalIndex?: number;
}

export interface GeneratedApiRoute {
  operationId?: string;
  summary?: string;
  stateSections?: string[];
  route: {
    tool: string;
    action: string;
    method: 'GET' | 'POST';
  };
  required?: string[];
  schema?: Record<string, GeneratedApiField>;
}

export const GENERATED_API_GAMESERVER_VERSION = 'v0.324.1';

export const GENERATED_API_ROUTES: Record<string, GeneratedApiRoute> = {
  'POST /api/v2/spacemolt_probe/ping': {
    operationId: 'probePing',
    summary: 'Ping probe',
    stateSections: ['ship', 'cargo'],
    route: {
      tool: 'spacemolt_probe',
      action: 'ping',
      method: 'POST',
    },
    required: ['id'],
    schema: {
      id: {
        type: 'string',
        positionalIndex: 0,
      },
    },
  },
};
`);
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  });

  test('generateApiMetadataFile fails when the spec lacks a gameserver version', () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'spacemolt-api-metadata-'));
    try {
      const openApiPath = path.join(tempDir, 'openapi.json');
      const outputPath = path.join(tempDir, 'generated', 'api-commands.ts');
      fs.writeFileSync(openApiPath, JSON.stringify({ openapi: '3.0.3', info: {}, paths: {} }));

      expect(() => generateApiMetadataFile({ openApiPath, outputPath })).toThrow(
        'OpenAPI spec is missing info.x-gameserver-version',
      );
      expect(fs.existsSync(outputPath)).toBe(false);
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  });
});
