import { describe, expect, test } from 'bun:test';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import {
  generate,
  type GeneratedApiRoute,
  generateApiMetadataFile,
  type OpenApiSpec,
  renderGeneratedApiRoutes,
} from './generate-api-metadata';
import {
  schemaAllowsType,
  schemaRequiredScalarType,
} from '../src/openapi-metadata';

describe('generate-api-metadata', () => {
  test('schema type helpers distinguish allowed shapes from required scalar coercion', () => {
    expect(schemaAllowsType('array', 'array')).toBe(true);
    expect(schemaAllowsType(['string', 'array'], 'array')).toBe(true);
    expect(schemaAllowsType(['string', 'array'], 'object')).toBe(false);
    expect(schemaAllowsType('future-shape', 'future-shape')).toBe(true);
    expect(schemaAllowsType(undefined, 'array')).toBe(false);

    expect(schemaRequiredScalarType('integer')).toBe('integer');
    expect(schemaRequiredScalarType(['integer', 'null'])).toBe('integer');
    expect(schemaRequiredScalarType(['integer', 'number', 'null'])).toBe('number');
    expect(schemaRequiredScalarType(['boolean', 'null'])).toBe('boolean');
    expect(schemaRequiredScalarType(['string', 'integer'])).toBeUndefined();
    expect(schemaRequiredScalarType(['array', 'null'])).toBeUndefined();
    expect(schemaRequiredScalarType('future-shape')).toBeUndefined();
    expect(schemaRequiredScalarType(undefined)).toBeUndefined();
  });

  test('generateApiRoutes preserves valid union types and omits malformed type values', () => {
    const spec = {
      info: { 'x-gameserver-version': 'v0.530.1' },
      paths: {
        '/api/v2/spacemolt_probe/union': {
          post: {
            operationId: 'probeUnion',
            requestBody: {
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: {
                      scalar: { type: 'string', description: 'Scalar field.' },
                      union: { type: ['string', 'array'], description: 'Union field.' },
                      empty: { type: [], description: 'Empty type array.' },
                      mixed: { type: ['string', 7], description: 'Mixed type array.' },
                    },
                  },
                },
              },
            },
          },
        },
      },
    } as unknown as OpenApiSpec;

    const route = generate(spec)['POST /api/v2/spacemolt_probe/union'];
    expect(route?.schema).toEqual({
      empty: { description: 'Empty type array.' },
      mixed: { description: 'Mixed type array.' },
      scalar: { type: 'string', description: 'Scalar field.' },
      union: { type: ['string', 'array'], description: 'Union field.' },
    });

    const rendered = renderGeneratedApiRoutes(
      { 'POST /api/v2/spacemolt_probe/union': route as GeneratedApiRoute },
      'v0.530.1',
    );
    expect(rendered).toContain('type?: string | string[];');
    expect(rendered).toContain("type: ['string', 'array']");
  });

  test('renderGeneratedApiRoutes includes CLI metadata only when present', () => {
    const route: GeneratedApiRoute = {
      operationId: 'toolAction',
      summary: 'Tool action',
      route: { tool: 'tool', action: 'action', method: 'POST' },
      cli: { command: 'tool_action', category: 'Tools' },
    };

    const renderedWithCli = renderGeneratedApiRoutes(
      {
        'POST /api/v2/tool/action': route,
      },
      'v0.324.1',
    );
    const renderedWithoutCli = renderGeneratedApiRoutes(
      {
        'POST /api/v2/tool/action': { ...route, cli: undefined },
      },
      'v0.324.1',
    );

    expect(renderedWithCli).toContain(
      '// Generated by scripts/generate-api-metadata.ts from spacemolt-docs/openapi.json for gameserver v0.324.1.',
    );
    expect(renderedWithCli).toContain('  cli?: {');
    expect(renderedWithCli).toContain("'tool_action'");
    expect(renderedWithoutCli).not.toContain('  cli?: {');
    expect(renderedWithCli).toContain("export const GENERATED_API_GAMESERVER_VERSION = 'v0.324.1';");
  });

  test('generateApiRoutes extracts query parameters when no request body schema exists', () => {
    const spec = {
      info: { 'x-gameserver-version': 'v0.522.0' },
      paths: {
        '/api/v2/notifications': {
          get: {
            operationId: 'getNotifications',
            summary: 'Poll pending notifications',
            parameters: [
              {
                name: 'limit',
                in: 'query',
                required: true,
                description: 'Maximum number of notifications to return.',
                schema: { type: 'integer', minimum: 1, maximum: 100 },
              },
              {
                name: 'clear',
                in: 'query',
                description: 'Whether returned notifications should be cleared.',
                schema: { type: 'boolean', description: 'Schema-level clear description.' },
              },
              {
                name: 'types',
                in: 'query',
                description: 'Filter by notification type.',
                schema: {
                  type: 'array',
                  items: { type: 'string', enum: ['chat', 'combat'] },
                },
              },
              {
                name: 'session_id',
                in: 'header',
                description: 'Ignored header parameter.',
                schema: { type: 'string' },
              },
              {
                name: '',
                in: 'query',
                description: 'Ignored empty-name parameter.',
                schema: { type: 'string' },
              },
              {
                name: 'missing_schema',
                in: 'query',
                description: 'Ignored schema-less parameter.',
              },
            ],
          },
        },
      },
    } as OpenApiSpec;

    const routes = generate(spec);

    expect(routes['GET /api/v2/notifications']).toEqual({
      operationId: 'getNotifications',
      summary: 'Poll pending notifications',
      route: {
        tool: 'notifications',
        action: 'notifications',
        method: 'GET',
      },
      required: ['limit'],
      schema: {
        clear: {
          type: 'boolean',
          description: 'Whether returned notifications should be cleared.',
        },
        limit: {
          type: 'integer',
          description: 'Maximum number of notifications to return.',
        },
        types: {
          type: 'array',
          enum: ['chat', 'combat'],
          description: 'Filter by notification type.',
        },
      },
    });
  });

  test('generateApiRoutes keeps request body schema ahead of query parameters', () => {
    const spec = {
      info: { 'x-gameserver-version': 'v0.522.0' },
      paths: {
        '/api/v2/spacemolt_probe/ping': {
          post: {
            operationId: 'probePing',
            summary: 'Ping probe',
            parameters: [
              {
                name: 'query_only',
                in: 'query',
                description: 'Should not appear when a body schema exists.',
                schema: { type: 'string' },
              },
            ],
            requestBody: {
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    required: ['id'],
                    properties: {
                      id: { type: 'string', description: 'Body ID.', 'x-positional-index': 0 },
                    },
                  },
                },
              },
            },
          },
        },
      },
    } as OpenApiSpec;

    expect(generate(spec)['POST /api/v2/spacemolt_probe/ping']).toEqual({
      operationId: 'probePing',
      summary: 'Ping probe',
      route: {
        tool: 'spacemolt_probe',
        action: 'ping',
        method: 'POST',
      },
      required: ['id'],
      schema: {
        id: {
          type: 'string',
          description: 'Body ID.',
          positionalIndex: 0,
        },
      },
    });
  });

  test('generateApiRoutes ignores paths outside the v2 API', () => {
    const spec = {
      info: { 'x-gameserver-version': 'v0.529.0' },
      paths: {
        '/api/catalog.json': {
          get: {
            operationId: 'getCatalog',
            summary: 'Get the complete catalog.',
          },
        },
        '/api/v2/spacemolt_probe/ping': {
          post: {
            operationId: 'probePing',
            summary: 'Ping probe',
          },
        },
      },
    } as OpenApiSpec;

    expect(generate(spec)).toEqual({
      'POST /api/v2/spacemolt_probe/ping': {
        operationId: 'probePing',
        summary: 'Ping probe',
        route: {
          tool: 'spacemolt_probe',
          action: 'ping',
          method: 'POST',
        },
      },
    });
  });

  test('generateApiMetadataFile writes deterministic TypeScript from a spec file', () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'spacemolt-api-metadata-'));
    try {
      const openApiPath = path.join(tempDir, 'openapi.json');
      const outputPath = path.join(tempDir, 'generated', 'api-commands.ts');
      const spec = {
        info: { 'x-gameserver-version': 'v0.324.1' },
        paths: {
          '/api/v2/spacemolt_probe/ping': {
            post: {
              operationId: 'probePing',
              summary: 'Ping probe',
              'x-state-sections': ['ship', 'cargo'],
              requestBody: {
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      required: ['id'],
                      properties: {
                        id: { type: 'string', 'x-positional-index': 0 },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      } as OpenApiSpec;

      fs.writeFileSync(openApiPath, JSON.stringify(spec));

      generateApiMetadataFile({ openApiPath, outputPath });

      const output = fs.readFileSync(outputPath, 'utf-8');
      expect(
        output,
      ).toBe(`// Generated by scripts/generate-api-metadata.ts from spacemolt-docs/openapi.json for gameserver v0.324.1.
// Do not edit by hand.

export interface GeneratedApiField {
  type?: string | string[];
  enum?: string[];
  description?: string;
  positionalIndex?: number;
}

export interface GeneratedApiRoute {
  operationId?: string;
  summary?: string;
  stateSections?: string[];
  route: {
    tool: string;
    action: string;
    method: 'GET' | 'POST';
  };
  required?: string[];
  schema?: Record<string, GeneratedApiField>;
}

export const GENERATED_API_GAMESERVER_VERSION = 'v0.324.1';

export const GENERATED_API_ROUTES: Record<string, GeneratedApiRoute> = {
  'POST /api/v2/spacemolt_probe/ping': {
    operationId: 'probePing',
    summary: 'Ping probe',
    stateSections: ['ship', 'cargo'],
    route: {
      tool: 'spacemolt_probe',
      action: 'ping',
      method: 'POST',
    },
    required: ['id'],
    schema: {
      id: {
        type: 'string',
        positionalIndex: 0,
      },
    },
  },
};
`);
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  });

  test('generateApiMetadataFile fails when the spec lacks a gameserver version', () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'spacemolt-api-metadata-'));
    try {
      const openApiPath = path.join(tempDir, 'openapi.json');
      const outputPath = path.join(tempDir, 'generated', 'api-commands.ts');
      fs.writeFileSync(openApiPath, JSON.stringify({ openapi: '3.0.3', info: {}, paths: {} }));

      expect(() => generateApiMetadataFile({ openApiPath, outputPath })).toThrow(
        'OpenAPI spec is missing info.x-gameserver-version',
      );
      expect(fs.existsSync(outputPath)).toBe(false);
    } finally {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  });
});
