import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  type GeneratedApiRoute,
  gameserverVersionFromSpec,
  generateApiRoutes,
  type OpenApiSpec,
} from '../src/openapi-metadata';

const root = path.join(import.meta.dir, '..');
const openApiPath = path.join(root, 'spacemolt-docs', 'openapi.json');
const outputPath = path.join(root, 'src', 'generated', 'api-commands.ts');
const biomeBin = path.join(root, 'node_modules', '.bin', process.platform === 'win32' ? 'biome.cmd' : 'biome');

export type { GeneratedApiRoute, OpenApiSpec } from '../src/openapi-metadata';
export { generateApiRoutes as generate } from '../src/openapi-metadata';

function formatGeneratedSource(source: string, filePath: string): string {
  const result = spawnSync(biomeBin, ['format', '--stdin-file-path', filePath], {
    cwd: root,
    input: source,
    encoding: 'utf-8',
  });

  if (result.status !== 0) {
    const detail = result.stderr || result.error?.message || 'unknown error';
    throw new Error(`Failed to format generated API metadata with Biome: ${detail}`);
  }

  return result.stdout;
}

export function renderGeneratedApiRoutes(routes: Record<string, GeneratedApiRoute>, gameserverVersion: string): string {
  const routeHasCliMetadata = Object.values(routes).some((route) => route.cli);

  return formatGeneratedSource(
    `// Generated by scripts/generate-api-metadata.ts from spacemolt-docs/openapi.json for gameserver ${gameserverVersion}.
// Do not edit by hand.

export interface GeneratedApiField {
  type?: string;
  enum?: string[];
  description?: string;
  positionalIndex?: number;
}

export interface GeneratedApiRoute {
  operationId?: string;
  summary?: string;
  route: {
    tool: string;
    action: string;
    method: 'GET' | 'POST';
  };
  required?: string[];
  schema?: Record<string, GeneratedApiField>;
${
  routeHasCliMetadata
    ? `  cli?: {
    command?: string;
    category?: string;
    hidden?: boolean;
  };
`
    : ''
}}

export const GENERATED_API_GAMESERVER_VERSION = '${gameserverVersion}';

export const GENERATED_API_ROUTES: Record<string, GeneratedApiRoute> = ${JSON.stringify(routes, null, 2)};
`,
    outputPath,
  );
}

export function generateApiMetadataFile(options: { openApiPath: string; outputPath: string }): void {
  const spec = JSON.parse(fs.readFileSync(options.openApiPath, 'utf-8')) as OpenApiSpec;
  const gameserverVersion = gameserverVersionFromSpec(spec);
  fs.mkdirSync(path.dirname(options.outputPath), { recursive: true });
  fs.writeFileSync(options.outputPath, renderGeneratedApiRoutes(generateApiRoutes(spec), gameserverVersion));
}

if (import.meta.main) {
  generateApiMetadataFile({ openApiPath, outputPath });
}
