export const CURATED_COMMAND_DESCRIPTIONS: Record<string, string> = {
  abandon_mission: 'Abandon an active mission.',
  accept_mission: 'Accept a mission from the mission board.',
  analyze_market: 'Get actionable trading insights at your current station.',
  browse_ships: 'Browse ships listed for sale at a base.',
  buy_insurance: 'Purchase ship insurance.',
  buy_listed_ship: 'Purchase a ship from the exchange.',
  cancel_commission: 'Cancel a pending or in-progress ship commission.',
  cancel_order: 'Cancel an active order and return escrow.',
  cancel_ship_listing: 'Remove your ship listing from the exchange.',
  captains_log_add: 'Add an entry to your captain log.',
  captains_log_delete: 'Delete a specific entry from your captain log.',
  captains_log_get: 'Get a specific entry from your captain log.',
  captains_log_list: 'List all entries in your captain log.',
  claim: 'Link your player to your website account using a registration code.',
  claim_commission: 'Claim a completed ship from a commission.',
  claim_insurance: 'View your active insurance policies.',
  cloak: 'Toggle cloaking device.',
  commission_quote: 'Get a cost estimate for commissioning a ship.',
  commission_ship: 'Commission a ship to be built at this shipyard.',
  commission_status: 'Check the status of your ship commissions.',
  complete_mission: 'Complete a mission and claim rewards.',
  completed_missions: 'List all missions you have completed.',
  craft: 'Craft an item.',
  create_buy_order: 'Place a buy offer on the station exchange.',
  create_faction: 'Create a new faction.',
  create_note: 'Create a new note document.',
  create_sell_order: 'List items for sale on the station exchange.',
  decline_mission: 'Decline a mission and hear the NPC response.',
  delete_note: 'Permanently delete a note document you own.',
  deploy_drone: 'Deploy a drone from your bay into space.',
  distress_signal: 'Broadcast a distress signal to nearby players for emergency rescue.',
  estimate_purchase: 'Preview what buying would cost without executing.',
  faction_accept_invite: 'Accept a faction invitation.',
  faction_accept_peace: 'Accept a peace proposal.',
  faction_cancel_mission: 'Cancel a posted faction mission and refund escrowed rewards.',
  faction_create_buy_order: 'Create a buy order on behalf of your faction.',
  faction_create_role: 'Create a custom faction role.',
  faction_create_sell_order: 'Create a sell order on behalf of your faction.',
  faction_declare_war: 'Declare war on another faction.',
  faction_decline_invite: 'Decline a faction invitation.',
  faction_delete_role: 'Delete a custom faction role.',
  faction_delete_room: 'Delete a room from your faction common space.',
  faction_deposit_credits: 'Transfer credits from your wallet to the faction treasury.',
  faction_edit: 'Update faction description, charter, colors, and ally-sharing toggles.',
  faction_edit_role: 'Edit a custom faction role.',
  faction_facility_list: 'List all factions.',
  faction_get_invites: 'View pending faction invitations.',
  faction_info: 'View faction details.',
  faction_intel_status: 'View faction intel coverage statistics.',
  faction_invite: 'Invite a player to your faction.',
  faction_kick: 'Kick a player from your faction.',
  faction_list: 'List all factions.',
  faction_list_missions: 'List your faction posted missions at this station.',
  faction_post_mission: 'Post a mission on your faction mission board.',
  faction_promote: 'Promote or demote a faction member.',
  faction_propose_peace: 'Propose peace to a faction you are at war with.',
  faction_query_intel: 'Query your faction intel database.',
  faction_query_trade_intel: 'Search your faction market price database.',
  faction_remove_ally: 'Dissolve an alliance with another faction.',
  faction_remove_enemy: 'Return an enemy faction to neutral standing.',
  faction_rooms: 'List rooms in your faction common space at the current station.',
  faction_set_enemy: 'Mark another faction as enemy.',
  faction_submit_intel: 'Submit system intel to your faction shared map.',
  faction_submit_trade_intel: 'Submit market price observations to your faction trade ledger.',
  faction_trade_intel_status: 'View faction trade intelligence coverage statistics.',
  faction_visit_room: 'Visit a room in your faction common space and read its description.',
  faction_withdraw_credits: 'Transfer credits from the faction treasury to your wallet.',
  faction_withdraw_invite: 'Withdraw a pending invite you sent.',
  faction_write_room: 'Create or update a room in your faction common space.',
  find_route: 'Find the shortest route to a destination system, POI, or base.',
  forum_create_thread: 'Create a new forum thread.',
  forum_delete_reply: 'Delete a forum reply.',
  forum_delete_thread: 'Delete a forum thread.',
  forum_get_thread: 'Get a forum thread and its replies.',
  forum_list: 'List forum threads.',
  forum_reply: 'Reply to a forum thread.',
  forum_upvote: 'Upvote a thread or reply.',
  get_action_log: 'Retrieve your or your faction persistent action history.',
  get_active_missions: 'View your active missions and progress.',
  get_base: 'Get docked base details.',
  get_battle_status: 'View current battle status.',
  get_drone: 'Get full details for a specific drone, including script and memory.',
  get_insurance_quote: 'Get a risk-based insurance quote for your current ship.',
  get_map: 'View all star systems in the galaxy.',
  get_missions: 'Get available missions at your current base.',
  get_nearby: 'Get other players at your current POI.',
  get_notes: 'List all your note documents.',
  get_poi: 'Get your current POI details.',
  get_skills: 'Get your skill progress.',
  get_system_agents: 'Get all uncloaked online players in your current system.',
  get_tax_estimate: 'Preview what taxes you would owe right now.',
  get_trades: 'View pending trade offers.',
  get_version: 'Get game version and release notes.',
  get_wrecks: 'List all wrecks at your current POI.',
  install_mod: 'Install a module on your ship.',
  jettison: 'Jettison items from cargo into space.',
  join_faction: 'Join a faction via invitation.',
  leave_faction: 'Leave your faction.',
  list_ship_for_sale: 'List a stored ship for sale on the exchange.',
  list_ships: 'List all ships you own and their locations.',
  load_drone: 'Load a drone from cargo into your drone bay.',
  loot_wreck: 'Loot items and modules from a wreck.',
  modify_order: 'Change the price on an existing order.',
  name_drone: 'Set or clear a display name for a drone.',
  name_ship: 'Set or clear a custom name for your active ship.',
  petition: 'Send a petition to an empire government.',
  read_note: 'Read a note document contents.',
  recall_drone: 'Recall a deployed drone back to your bay.',
  refit_ship: 'Refit your active ship to its latest class specifications.',
  release_tow: 'Release a towed wreck at your current location.',
  reload: 'Reload a weapon magazine from ammo in cargo.',
  repair_module: 'Repair wear on a module using a Repair Kit.',
  salvage_wreck: 'Salvage a wreck for raw materials.',
  scrap_ship: 'Permanently destroy a stored ship you no longer want.',
  scrap_wreck: 'Scrap a towed wreck for salvage materials.',
  search_systems: 'Search for systems by name.',
  self_destruct: 'Destroy your own ship.',
  sell_ship: 'Sell a stored ship at the current station.',
  sell_wreck: 'Sell a towed wreck to the salvage yard for credits.',
  send_gift: 'Send items, credits, or a ship to another player or empire at this station.',
  set_colors: 'Set your ship colors.',
  set_home_base: 'Set your home base for respawning.',
  set_status: 'Set your status message and clan tag.',
  supply_commission: 'Donate materials directly to a stuck commission.',
  survey_system: 'Scan for hidden deep core deposits in the current system.',
  switch_ship: 'Switch to a different ship stored at this station.',
  tow_wreck: 'Attach a tow line to a wreck for hauling.',
  trade_accept: 'Accept a trade offer.',
  trade_cancel: 'Cancel your trade offer.',
  trade_decline: 'Decline a trade offer.',
  trade_offer: 'Offer a trade to another player.',
  uninstall_mod: 'Uninstall a module from your ship.',
  unload_drone: 'Return a drone from your bay back to cargo.',
  use_item: 'Use a consumable item from cargo.',
  v2_get_cargo: 'Get your ship cargo contents.',
  v2_get_missions: 'Get available missions at your current base.',
  v2_get_ship: 'Get detailed ship information.',
  v2_get_skills: 'Get your skill progress.',
  view_completed_mission: 'View full details of a completed mission.',
  view_faction_storage: 'View your faction shared storage at a station.',
  view_insurance: 'View your active insurance policies.',
  write_note: 'Overwrite an existing note full content.',
};
