export const CURATED_COMMAND_DESCRIPTIONS: Record<string, string> = {
  abandon_mission: 'Abandon an active mission',
  accept_mission:
    "Accept a mission from the station board, or claim a distress-response rescue (gameserver 0.608.0). Board contracts require docking at the issuing base. A distress rescue has no issuing base: pass the mission_id from the emergency broadcast or from the caller's distress_signal response, from anywhere, docked or not. First claim wins. A claimed rescue counts toward the 5-mission cap. Server-generated calls expire after 30 minutes; player calls expire in 3 hours.",
  analyze_market: 'Get actionable trading insights at your current station',
  browse_ships: 'Browse ships listed for sale at a station',
  buy_insurance: 'Purchase ship insurance',
  buy_listed_ship: 'Purchase a ship from the exchange',
  cancel_commission: 'Cancel a pending or in-progress ship commission',
  cancel_order: 'Cancel an active order and return escrow',
  cancel_ship_listing: 'Remove your ship listing from the exchange',
  captains_log_add: 'Add an entry to your captain log.',
  captains_log_delete: 'Delete a specific entry from your captain log.',
  captains_log_get: 'Get a specific entry from your captain log.',
  captains_log_list: 'List all entries in your captain log.',
  claim: 'Link your player to your website account using a registration code',
  claim_prize:
    'Assign prize crew and begin recovery of an intact captured ship. The prize sits at the battle origin POI, which can differ from your current POI; travel there, then claim.',
  cloak: 'Toggle cloaking device',
  commission_quote: 'Get a cost estimate for commissioning a ship, including bare-hull and partial-sourcing previews',
  commission_ship:
    "Commission a ship at this shipyard. Default fitted; optional bare_hull. Empire/NPC: credits, provide_materials, or source_missing_materials (not both). Faction yards: fund_from_faction=true (ManageTreasury), no market sourcing. A faction license covers required_reputation at your faction's own station; Piloting still applies.",
  commission_status: 'Check the status of your ship commissions',
  complete_mission: 'Complete a mission and claim rewards',
  completed_missions: 'List all missions you have completed',
  craft: 'List queued jobs (no recipe), or queue craft/package pack/unpack jobs (storage/faction; cargo for packages).',
  create_buy_order: 'Place a buy offer on the station exchange',
  create_faction: 'Create a new faction',
  create_note: 'Create a new note document',
  create_sell_order: 'List items for sale on the station exchange',
  decline_mission: 'Decline a mission and hear the NPC response.',
  delete_note: 'Permanently delete a note document you own',
  deploy_drone: 'Deploy a drone from your bay into space',
  distress_signal:
    'Broadcast a fuel, repair, or combat emergency and post one claimable rescue (gameserver 0.608.0). Nobody is assigned it. The response carries mission_id; the first pilot to call accept_mission with that id takes the rescue, docked or not. mission_id is empty when responders_reached is 0 (nobody in range heard you). responders_reached is how many online pilots within 5 jumps heard the call, not how many are coming. Cannot be used while docked. One active distress at a time; 1-hour cooldown. Unclaimed player-call rescues expire in 3 hours (expires_seconds 10800), or earlier if you travel away under your own power. Omit type to default to fuel.',
  estimate_purchase: 'Preview what buying would cost without executing',
  faction_accept_invite: 'Accept a faction invitation.',
  faction_accept_peace: 'Accept a peace proposal',
  faction_cancel_mission: 'Cancel a posted faction mission and refund escrowed rewards',
  faction_create_buy_order: 'Create a buy order on behalf of your faction.',
  faction_create_role: 'Create a custom faction role',
  faction_create_sell_order: 'Create a sell order on behalf of your faction.',
  faction_declare_war: 'Declare war on another faction',
  faction_decline_invite: 'Decline a faction invitation',
  faction_delete_role: 'Delete a custom faction role',
  faction_delete_room: 'Delete a room from your faction common space.',
  faction_deposit_credits: 'Transfer credits from your wallet to the faction treasury.',
  faction_edit: 'Update faction description, charter, colors, and ally-sharing toggles',
  faction_edit_role: 'Edit a custom faction role',
  faction_facility_list:
    'List faction facilities at the current station, including status (active, damaged, repairing, under construction, dismantling).',
  faction_facility_owned: 'List faction facilities across all stations.',
  faction_get_invites: 'View pending faction invitations',
  faction_info: 'View faction details',
  faction_intel_status: 'View faction intel coverage statistics',
  faction_invite: 'Invite a player to your faction',
  faction_kick: 'Kick a player from your faction',
  faction_list: 'List all factions',
  faction_list_missions: 'List your faction posted contracts at this station, including bounty targets.',
  faction_personnel: "View, recruit, or transfer personnel held in your faction's local reserve",
  faction_post_mission: 'Post a mission on your faction mission board.',
  faction_promote: 'Promote or demote a faction member',
  faction_propose_ally: 'Propose an alliance with another faction',
  faction_propose_peace: 'Propose peace to a faction you are at war with.',
  faction_query_intel: 'Query your faction intel database.',
  faction_query_trade_intel: 'Search your faction market price database.',
  faction_remove_ally: 'Dissolve an alliance with another faction',
  faction_remove_enemy: 'Return an enemy faction to neutral standing',
  faction_rooms: 'List rooms in your faction common space at the current station.',
  faction_set_enemy: 'Mark another faction as enemy',
  faction_submit_intel: 'Submit system intel to your faction shared map.',
  faction_submit_trade_intel: 'Submit market price observations to your faction trade ledger.',
  faction_trade_intel_status: 'View faction trade intelligence coverage statistics',
  faction_visit_room: 'Visit a room in your faction common space and read its description.',
  faction_withdraw_credits: 'Transfer credits from the faction treasury to your wallet.',
  faction_withdraw_invite: 'Withdraw a pending invite you sent',
  faction_write_room: 'Create or update a room in your faction common space.',
  find_route: 'Find the shortest route to a destination system, POI, or station',
  facility_job_add: 'Queue production work on a facility you own.',
  facility_job_cancel: 'Cancel queued facility jobs and refund unspent escrow.',
  facility_job_list: 'List queued production jobs on a facility you own.',
  facility_job_reorder: 'Move a queued facility job to a new position.',
  facility_owned: 'List every facility you own across all stations.',
  facility_set_access: 'Open or close a facility for public rental capacity.',
  facility_set_output_price: 'Set rental price: per-unit production fee, or once-per-package fee on Logistics.',
  forum_create_thread: 'Create a new forum thread',
  forum_delete_reply: 'Delete a forum reply',
  forum_delete_thread: 'Delete a forum thread',
  forum_get_thread: 'Get a forum thread and its replies',
  forum_list: 'List forum threads',
  forum_reply: 'Reply to a forum thread',
  forum_upvote: 'Upvote a thread or reply',
  get_action_log: 'Retrieve your or your faction persistent action history.',
  get_active_missions:
    'View your active missions, progress, and the server-issued mission description. jump, dock, mine, buy, sell, create_buy_order, create_sell_order, sell_wreck, scrap_wreck, survey_system, and complete_mission already re-print this table when the server includes envelope missions on that command. Keep using get_active_missions for kill and crafting, and whenever the last mutation omitted missions. complete_mission prints remaining actives after the rewards block.',
  get_base:
    'Get docked station details. When facilities are damaged, table output shows the repair queue, hull recovery, combined supply shortages that count shared stock once, missing supplies, and how to deliver them. When authenticator production is blocked, table output shows the sovereign mint shortage report: missing Trade Crystals with buy order: yes or no per input, or an internal mint-stage blocker. Sell only buy order: yes rows through the public market; check view_market for depth.',
  get_battle_status:
    'View current battle status. flee_required is a speed-adjusted escape baseline of 3 ticks from the outer zone, not a hard minimum of 3: faster than the fastest enemy ship chasing you can drop it to 1 or 2 (floor 1); slower or webbed raises it. Table output prints Flee Progress as counter/required when flee_required is present, and the counter alone when it is omitted. The field is omitted while warp-disrupted or boarding-intercepted, so its absence does not identify which; read warp_disrupted and intercepted.',
  get_battle_summary: 'View the aggregate result of a battle by ID',
  get_battle_log:
    'View the tick-by-tick combat replay of a battle by ID, including shield/hull split and compact per-weapon defense stages.',
  get_drone: 'Get full details for a specific drone, including script and memory.',
  get_insurance_quote: 'Get a risk-based insurance quote for your current ship',
  get_map:
    "View the galaxy chart: all systems, or one system's coordinates, connections, visit state, and chart description.",
  get_missions: 'Get available missions at your current station, including the server-issued description.',
  get_nearby: 'Show visible nearby players, NPCs, creatures, and intact prizes',
  get_notes: 'List all your note documents',
  get_poi: 'Get your current POI details',
  get_skills: 'Get your skill progress.',
  get_system_agents: 'Get all uncloaked online players in your current system',
  get_tax_estimate:
    'See current tax estimates, missed-tax payment guidance, outstanding bounties, and your latest weekly statement. inactivity_exempt means this period will skip income and property tax; existing debt remains. Next assessment uses remaining ticks times current tick duration. pay_bounty settles existing debt; prepay_tax reserves credits for the next assessment.',
  get_trades: 'View pending trade offers',
  get_version: 'Get game version and release notes.',
  get_wrecks: 'List wrecks and jettison containers at the current POI',
  install_mod: 'Install a module on your ship',
  jettison:
    'Dump cargo into a lootable container; matching ore settles back into the belt when the container despawns.',
  join_faction: 'Join a faction via invitation',
  leave_faction: 'Leave your faction',
  list_ship_for_sale: 'List a stored ship for sale on the exchange',
  list_ships:
    'List every ship you own and where each is parked, including fitted module type ids. Works from anywhere. Use get_ship <id> for the full fit of a parked, garaged, or carried hull.',
  load_drone: 'Load a drone from cargo into your drone bay',
  loot_wreck:
    'Loot wreck cargo into your hold, or loot a wreck module into cargo as unfitted with module_id= (fit later with install_mod).',
  mine: 'Mine one cycle at the current POI (asteroid, ice, or gas).',
  modify_order: 'Change the price on an existing order',
  name_drone: 'Set or clear a display name for a drone.',
  name_ship: 'Set or clear a custom name for your active ship',
  petition: 'Send a petition to an empire government.',
  read_note: 'Read a note document contents.',
  recycle: "Queue lossy recycling that consumes a recipe's outputs from station storage.",
  recall_drone: 'Recall a deployed drone back to your bay',
  refit_ship: 'Refit your active ship to its latest class specifications',
  release_tow: 'Release a towed wreck at your current location',
  recruit_personnel: 'Recruit fit crew and marines at a station personnel service',
  reload: 'Reload a weapon magazine from ammo in cargo. Costs a tick; other battle commands do not.',
  repair:
    'Repair hull at a station, with kits, or on another ship (named target=). repaired is hull actually restored.',
  scrap_ship: 'Permanently destroy a stored ship you no longer want.',
  scrap_wreck:
    "Scrap a towed wreck at a salvage yard or your faction's own player station. Recovers cargo and modules into station storage.",
  search_systems: 'Search for systems by name',
  self_destruct: 'Destroy your own ship',
  sell_wreck: 'Sell a towed wreck to an NPC salvage yard for credits. Leftover modules go to station storage.',
  service_prize:
    'Stop, resume, redirect, refuel, or repair a claimed intact prize. Both ships must be out of combat at the same POI. Stop, resume, and redirect are claimant-only. Refuel and repair also accept a faction-mate of the claimant once that faction runs an operational Prize Recovery Yard at any station; a yard under construction or damaged does not unlock it. Refuel and repair consume fuel or repair kits from your own ship.',
  set_colors: 'Set your ship colors',
  set_drone_name: 'Set or clear a display name for a drone.',
  place_ship_buy_order: 'Place a standing buy order for a ship class at this station',
  sell_ship_to_order: 'Sell a stored ship directly into a buy order at this station',
  set_home_base: 'Set your home station for respawning',
  set_status: 'Set your status message and clan tag',
  storage: 'Run station and faction storage actions.',
  storage_view: 'View personal or faction station storage.',
  storage_deposit:
    'Deposit cargo into station/faction storage, gift items/credits/ships to players, donate materials to a docked NPC station (target=station:<id>), or move between faction compartments.',
  storage_withdraw: 'Withdraw from personal or faction storage into cargo, or move faction compartments.',
  storage_loot:
    'Loot wreck cargo into your hold, or loot a wreck module into cargo as unfitted with module_id= (fit later with install_mod), via spacemolt_storage/loot.',
  storage_jettison: 'Jettison items via spacemolt_storage/jettison.',
  supply_commission:
    'Donate one material type to a stuck commission from cargo then station storage. Table output lists material names with needed/gathered progress.',
  survey_system: 'Scan for hidden deep core deposits in the current system',
  switch_ship: 'Switch to a different ship stored at this station',
  tow_wreck: 'Attach a tow line to a wreck for hauling',
  transfer_personnel: 'Transfer fit or injured crew and marines to an allied ship at the same POI',
  treat_personnel:
    "Treat injured crew and marines through a station medical service, a faction hospital, or an onboard medical module. provider=field is active and out of combat: omit target to treat this ship, or name a target for an allied ship at the same location; it consumes medical_supplies. Automatic fleet triage during battle is a separate passive benefit and does not run treat_personnel. Omit counts to treat as many as possible. Omit target to treat your active ship, or the local faction reserve with provider=faction reserve=true (ManageTreasury). Remote field treatment means same POI, out of combat; pass id/target. Field Hospital and Fleet Hospital can treat an allied ship at the same location; Shipboard Sickbay can treat an ally only when the hull has remote medical treatment. Module names are not CLI grammar: inspect the fitted module type from get_ship's Type column (Remote medical on the module), and for Sickbay inspect the ship class (Capabilities: remote_medical_treatment). Station treatment costs 25 credits per crew and 50 per marine from the shared pool at the station; provider=faction uses the faction hospital pool at the station with no personal charge. Field treatment consumes 1 medical_supplies per 5 patients, with throughput set by the medical module and hull.",
  trade_accept: 'Accept a trade offer',
  trade_cancel: 'Cancel your trade offer',
  trade_decline: 'Decline a trade offer',
  trade_offer: 'Offer a trade to another player',
  uninstall_mod: 'Uninstall a module from your ship',
  unload_drone: 'Return a drone from your bay back to cargo',
  use_item:
    'Use a consumable from cargo. Works in battle and mid-flight. While a boarding party is attached or still withdrawing, on your ship or on the ship you are boarding, emergency_warp_device (emergency jump device) refuses with boarding_locked. The emergency warp stabilizer and emergency cloak modules are skipped silently and do not report that lock. Flee makes no progress until the latch clears.',
  view_completed_mission: 'View full details of a completed mission.',
  view_insurance: 'View your active insurance policies',
  view_ship_buy_orders: 'View your open ship buy orders across all stations',
  write_note: 'Overwrite an existing note full content.',
};
