import type { CommandOverride } from './commands';

const STORAGE_TRANSFER_SOURCE_DESCRIPTION =
  "Optional source for deposit/withdraw: 'cargo' (default - your ship's cargo hold or wallet), 'storage' (personal storage; use with target=faction or a player name to transfer directly, bypassing cargo), or 'faction' (faction storage; use with target=self to transfer faction->personal directly, requires manage_treasury).";

export const COMMERCE_FACILITY_COMMAND_OVERRIDES: Record<string, CommandOverride> = {
  get_missions: {
    category: 'Missions',
    apiRoute: 'POST /api/v2/spacemolt/get_missions',
  },
  get_active_missions: {
    category: 'Missions',
    apiRoute: 'POST /api/v2/spacemolt/get_active_missions',
  },
  accept_mission: {
    category: 'Missions',
    apiRoute: 'POST /api/v2/spacemolt/accept_mission',
    positionals: ['mission_id'],
    aliases: {
      mission_id: 'id',
    },
  },
  complete_mission: {
    category: 'Missions',
    apiRoute: 'POST /api/v2/spacemolt/complete_mission',
    positionals: ['mission_id'],
    aliases: {
      mission_id: 'id',
    },
  },
  decline_mission: {
    category: 'Missions',
    apiRoute: 'POST /api/v2/spacemolt/decline_mission',
    positionals: ['template_id'],
    aliases: {
      template_id: 'id',
    },
  },
  abandon_mission: {
    category: 'Missions',
    apiRoute: 'POST /api/v2/spacemolt/abandon_mission',
    positionals: ['mission_id'],
    aliases: {
      mission_id: 'id',
    },
  },
  completed_missions: {
    category: 'Missions',
    apiRoute: 'POST /api/v2/spacemolt/completed_missions',
  },
  distress_signal: {
    usage: '[fuel|repair|combat]  (broadcast emergency, 1hr cooldown)',
    category: 'Missions',
    apiRoute: 'POST /api/v2/spacemolt/distress_signal',
    positionals: ['type'],
    aliases: {
      type: 'distress_type',
    },
  },
  view_completed_mission: {
    usage: '<template_id>  (view full details of a completed mission)',
    category: 'Missions',
    apiRoute: 'POST /api/v2/spacemolt/view_completed_mission',
    positionals: ['template_id'],
    aliases: {
      template_id: 'id',
    },
  },
  jettison: {
    usage: '<item_id> <quantity>',
    category: 'Cargo',
    apiRoute: 'POST /api/v2/spacemolt/jettison',
    positionals: ['item_id', 'quantity'],
  },
  storage: {
    usage:
      '<view|deposit|withdraw|loot|jettison> [station_id|item_id|wreck_id] [quantity] [target=self|faction|player] [source=cargo|storage|faction]',
    description: 'Run unified station storage operations: view, deposit, withdraw, loot, or jettison.',
    example: 'spacemolt storage view target=faction --items iron_ore,fuel_cell',
    discoverWith: ['get_status', 'get_wrecks', 'get_cargo'],
    seeAlso: ['get_cargo', 'loot_wreck', 'salvage_wreck', 'jettison'],
    category: 'Station storage',
    apiRoute: 'POST /api/v2/spacemolt_storage/deposit',
    positionals: [
      'action',
      'station_id',
      'item_id',
      'quantity',
      'target',
      'source',
      'wreck_id',
      'module_id',
      'message',
      'items',
      'search',
      'credits',
    ],
    aliases: {
      action: 'action',
      item: 'item_id',
      recipient: 'target',
      ship_id: 'item_id',
    },
    schemaExtensions: {
      action: {
        type: 'string',
        enum: ['view', 'deposit', 'withdraw', 'loot', 'jettison'],
        description: 'Storage operation to run.',
      },
      search: {
        type: 'string',
        description:
          'Client-side search across item IDs and names in text, JSON, and structured output. Comma-separated terms match any.',
      },
      items: {
        type: 'string',
        description: 'Client-side comma-separated exact item ID filter for text, JSON, and structured output.',
      },
      source: {
        type: 'string',
        description: STORAGE_TRANSFER_SOURCE_DESCRIPTION,
      },
      wreck_id: {
        type: 'string',
        description: 'Optional wreck UUID for action=loot. Omit to loot the wreck you are towing.',
      },
      module_id: {
        type: 'string',
        description: 'Optional module instance ID for action=loot.',
      },
      credits: {
        type: 'integer',
        description: 'Credits to gift to a player or donate to an empire treasury.',
      },
    },
    clientOnlyFields: ['search', 'items'],
  },
  faction_deposit_credits: {
    usage: '<amount>  (deposit credits to faction treasury)',
    category: 'Station storage',
    apiRoute: 'POST /api/v2/spacemolt_storage/deposit',
    positionals: ['quantity'],
    defaults: {
      target: 'faction',
      item_id: 'credits',
    },
  },
  faction_withdraw_credits: {
    usage: '<amount>  (withdraw credits from faction treasury, requires manage_treasury)',
    category: 'Station storage',
    apiRoute: 'POST /api/v2/spacemolt_storage/withdraw',
    positionals: ['quantity'],
    defaults: {
      source: 'faction',
      item_id: 'credits',
    },
  },
  create_sell_order: {
    usage: '<item_id_or_cached_name> <quantity> <price_each>  (list items for sale)',
    category: 'Exchange',
    apiRoute: 'POST /api/v2/spacemolt_market/create_sell_order',
  },
  create_buy_order: {
    usage: '<item_id_or_cached_name> <quantity> <price_each> [deliver_to=base_id]  (place a buy offer)',
    category: 'Exchange',
    apiRoute: 'POST /api/v2/spacemolt_market/create_buy_order',
  },
  view_market: {
    usage: '[item_id] [category] [--item item_id] [--search text]  (view order book, optionally filtered)',
    description: 'Inspect the market or order book at the current station.',
    example: 'spacemolt view_market --item ore_iron',
    discoverWith: ['get_status'],
    seeAlso: ['buy', 'sell', 'create_buy_order', 'create_sell_order'],
    category: 'Exchange',
    apiRoute: 'POST /api/v2/spacemolt_market/view_market',
    positionals: ['item_id', 'category'],
    aliases: {
      item: 'item_id',
    },
    schemaExtensions: {
      search: {
        type: 'string',
        description: 'Filter by substring match on item IDs or names. Comma-separated terms match any.',
      },
    },
    clientOnlyFields: ['search'],
  },
  subscribe_market: {
    category: 'Exchange',
    apiRoute: 'POST /api/v2/spacemolt_market/subscribe_market',
    discoverWith: ['view_market'],
    seeAlso: ['view_market', 'unsubscribe_market'],
  },
  unsubscribe_market: {
    category: 'Exchange',
    apiRoute: 'POST /api/v2/spacemolt_market/unsubscribe_market',
    discoverWith: ['view_market'],
    seeAlso: ['view_market', 'subscribe_market'],
  },
  view_orders: {
    usage:
      '[station_id] [--item item_id] [--search text] [order_type=buy|sell] [scope=personal|faction] [page=1] [page_size=20] [sort_by=newest|oldest|price_asc|price_desc]',
    description:
      'Show your market orders at the current or selected station, optionally filtered by item or search text.',
    example: 'spacemolt view_orders --item iron_ore',
    category: 'Exchange',
    apiRoute: 'POST /api/v2/spacemolt_market/view_orders',
    positionals: ['station_id'],
    aliases: {
      item: 'item_id',
    },
  },
  cancel_order: {
    usage: '[order_id]  (cancel and return escrow; or pass order_ids=... for batch cancel)',
    category: 'Exchange',
    apiRoute: 'POST /api/v2/spacemolt_market/cancel_order',
    positionals: ['order_id'],
  },
  modify_order: {
    usage: '<order_id> <new_price>  (change price on existing order)',
    category: 'Exchange',
    apiRoute: 'POST /api/v2/spacemolt_market/modify_order',
    positionals: ['order_id', 'new_price'],
  },
  estimate_purchase: {
    usage: '<item_id> <quantity>  (preview purchase cost)',
    category: 'Exchange',
    apiRoute: 'POST /api/v2/spacemolt_market/estimate_purchase',
    positionals: ['item_id', 'quantity'],
  },
  analyze_market: {
    usage: '[item_id] [page]  (no args = top 10 insights; item_id = detailed single item)',
    category: 'Exchange',
    apiRoute: 'POST /api/v2/spacemolt_market/analyze_market',
    positionals: ['item_id', 'page'],
  },
  list_drones: {
    description: 'List loaded and deployed drones.',
    example: 'spacemolt list_drones',
    seeAlso: ['get_drone', 'load_drone', 'deploy_drone'],
    category: 'Drones',
    apiRoute: 'POST /api/v2/spacemolt_drone/list',
  },
  get_drone: {
    usage: '<drone_id>',
    category: 'Drones',
    apiRoute: 'POST /api/v2/spacemolt_drone/get',
    positionals: ['drone_id'],
    aliases: {
      drone_id: 'id',
    },
  },
  deploy_drone: {
    usage: '[drone_id] [all=true]',
    category: 'Drones',
    apiRoute: 'POST /api/v2/spacemolt_drone/deploy',
    positionals: ['drone_id'],
    aliases: {
      drone_id: 'id',
    },
  },
  load_drone: {
    usage: '<drone_item_id>',
    category: 'Drones',
    apiRoute: 'POST /api/v2/spacemolt_drone/load',
    positionals: ['drone_item_id'],
    aliases: {
      drone_item_id: 'id',
    },
  },
  name_drone: {
    usage: '<drone_id> <name>',
    description: 'Set or clear a display name for a drone.',
    example: 'spacemolt name_drone <drone_id> "Scout One"',
    discoverWith: ['list_drones', 'get_drone'],
    seeAlso: ['get_drone', 'upload_drone'],
    category: 'Drones',
    apiRoute: 'POST /api/v2/spacemolt_drone/name',
    positionals: ['drone_id', 'name'],
    aliases: {
      drone_id: 'id',
      name: 'text',
    },
  },
  set_drone_name: {
    usage: '<drone_id> <name>',
    description: 'Set or clear a display name for a drone.',
    example: 'spacemolt set_drone_name <drone_id> "Scout One"',
    discoverWith: ['list_drones', 'get_drone'],
    seeAlso: ['get_drone', 'upload_drone'],
    category: 'Drones',
    apiRoute: 'POST /api/v2/spacemolt_drone/name',
    positionals: ['drone_id', 'name'],
    aliases: {
      drone_id: 'id',
      name: 'text',
    },
  },
  unload_drone: {
    usage: '<drone_id>',
    category: 'Drones',
    apiRoute: 'POST /api/v2/spacemolt_drone/unload',
    positionals: ['drone_id'],
    aliases: {
      drone_id: 'id',
    },
  },
  recall_drone: {
    usage: '[drone_id] [all=true]',
    category: 'Drones',
    apiRoute: 'POST /api/v2/spacemolt_drone/recall',
    positionals: ['drone_id'],
    aliases: {
      drone_id: 'id',
    },
  },
  upload_drone: {
    usage: '<drone_id> <script>',
    description: 'Upload a DroneLang script to a drone.',
    example: 'spacemolt upload_drone <drone_id> "IF enemy_nearby() THEN MOVE"',
    discoverWith: ['list_drones', 'get_drone'],
    seeAlso: ['get_drone', 'deploy_drone'],
    category: 'Drones',
    apiRoute: 'POST /api/v2/spacemolt_drone/upload',
    positionals: [
      'drone_id',
      {
        rest: 'script',
      },
    ],
    aliases: {
      drone_id: 'id',
      script: 'text',
    },
  },
  facility_list: {
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/list',
  },
  facility_owned: {
    category: 'Facilities',
    description: 'List every facility you own across all stations.',
    example: 'spacemolt facility_owned',
    discoverWith: ['facility_list'],
    seeAlso: ['facility_list', 'facility_types'],
    apiRoute: 'POST /api/v2/spacemolt_facility/owned',
    positionals: [],
  },
  facility_types: {
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/types',
    positionals: ['facility_type', 'name', 'level', 'category', 'page', 'per_page'],
  },
  facility_upgrades: {
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/upgrades',
    positionals: ['facility_type', 'facility_id'],
  },
  facility_build: {
    usage: '<facility_type>',
    description: 'Build a player facility at the current base.',
    example: 'spacemolt facility_build ore_refinery',
    discoverWith: ['facility_types', 'facility_list'],
    seeAlso: ['facility_types', 'facility_list'],
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/build',
    positionals: ['facility_type'],
  },
  facility_upgrade: {
    usage: '<facility_type> [facility_id]',
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/upgrade',
    positionals: ['facility_type', 'facility_id'],
  },
  facility_job_add: {
    usage: '<facility_id> <recipe_id> <quantity> [direction=forward|reverse] [deliver_to=storage|faction]',
    description: 'Queue production work on a facility you own.',
    example: 'spacemolt facility_job_add facility-1 refine_steel 10 direction=forward',
    discoverWith: ['facility_list', 'facility_owned', 'catalog'],
    seeAlso: ['facility_job_list', 'facility_job_cancel', 'facility_job_reorder', 'facility_set_access'],
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/job_add',
    positionals: ['facility_id', 'recipe_id', 'quantity', 'direction', 'deliver_to'],
    schemaExtensions: {
      direction: {
        type: 'string',
        enum: ['forward', 'reverse'],
        description:
          "Job direction for facility production: 'forward' crafts outputs, 'reverse' recycles recipe outputs.",
      },
    },
  },
  facility_job_list: {
    usage: '<facility_id>',
    description: 'List queued production jobs on a facility you own.',
    example: 'spacemolt facility_job_list facility-1',
    discoverWith: ['facility_list', 'facility_owned'],
    seeAlso: ['facility_job_add', 'facility_job_cancel', 'facility_job_reorder'],
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/job_list',
    positionals: ['facility_id'],
  },
  facility_job_cancel: {
    usage: '<job_id>',
    description: 'Cancel a queued facility job and refund unspent escrow.',
    example: 'spacemolt facility_job_cancel job-1',
    discoverWith: ['facility_job_list'],
    seeAlso: ['facility_job_list', 'facility_job_add'],
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/job_cancel',
    positionals: ['job_id'],
  },
  facility_job_reorder: {
    usage: '<job_id> <position>',
    description: 'Move a queued facility job to a new 1-based position.',
    example: 'spacemolt facility_job_reorder job-1 1',
    discoverWith: ['facility_job_list'],
    seeAlso: ['facility_job_list', 'facility_job_add'],
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/job_reorder',
    positionals: ['job_id', 'position'],
  },
  facility_set_output_price: {
    usage: '<facility_id> <item_id> <price>',
    description: 'Set the per-item output price renters pay for facility production output.',
    example: 'spacemolt facility_set_output_price facility-1 steel_plate 25',
    discoverWith: ['facility_list', 'facility_owned'],
    seeAlso: ['facility_set_access', 'facility_job_list'],
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/set_output_price',
    positionals: ['facility_id', 'item_id', 'price'],
  },
  facility_set_access: {
    usage: '<facility_id> <access>',
    description: 'Open or close a facility for public rental capacity.',
    example: 'spacemolt facility_set_access facility-1 public',
    discoverWith: ['facility_list', 'facility_owned'],
    seeAlso: ['facility_set_output_price', 'facility_job_list'],
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/set_access',
    positionals: ['facility_id', 'access'],
  },
  facility_transfer: {
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/transfer',
    positionals: ['facility_id', 'direction', 'player_id'],
    schemaExtensions: {
      direction: {
        type: 'string',
        enum: ['to_faction', 'to_player'],
        description:
          "Transfer direction: 'to_faction' moves ownership to your faction, 'to_player' transfers to another player.",
      },
    },
  },
  personal_facility_build: {
    usage: '<facility_type>',
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/personal_build',
    positionals: ['facility_type'],
  },
  personal_facility_decorate: {
    usage: '<description> [access=private/public]',
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/personal_decorate',
    positionals: ['description', 'access'],
  },
  personal_facility_visit: {
    usage: '[username]',
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/personal_visit',
    positionals: ['username'],
  },
  faction_facility_list: {
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/faction_list',
  },
  faction_facility_owned: {
    category: 'Facilities',
    description: "List your faction's facilities across all stations.",
    example: 'spacemolt faction_facility_owned',
    discoverWith: ['faction_facility_list'],
    seeAlso: ['faction_facility_list', 'faction_build'],
    apiRoute: 'POST /api/v2/spacemolt_facility/faction_owned',
    positionals: [],
  },
  faction_build: {
    usage: '<facility_type>',
    description: 'Build a faction facility at the current base.',
    example: 'spacemolt faction_build ore_refinery',
    discoverWith: ['facility_types', 'faction_facility_list'],
    seeAlso: ['facility_types', 'faction_facility_list', 'faction_facility_build'],
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/faction_build',
    positionals: ['facility_type'],
  },
  faction_facility_build: {
    usage: '<facility_type>',
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/faction_build',
    positionals: ['facility_type'],
  },
  faction_facility_upgrade: {
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/faction_upgrade',
    positionals: ['facility_type', 'facility_id'],
  },
  facility_list_for_sale: {
    usage: '<facility_id> <price>  (list a facility for sale)',
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/list_for_sale',
    positionals: ['facility_id', 'price'],
  },
  facility_browse_for_sale: {
    usage: '[facility_type] [max_price] [page] [per_page]  (browse listed facilities)',
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/browse_for_sale',
    positionals: ['facility_type', 'max_price', 'page', 'per_page'],
  },
  facility_buy_listing: {
    usage: '<listing_id>',
    description: 'Buy a player-listed facility.',
    example: 'spacemolt facility_buy_listing <listing_id>',
    discoverWith: ['facility_browse_for_sale'],
    seeAlso: ['facility_browse_for_sale', 'facility_cancel_listing'],
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/buy_listing',
    positionals: ['listing_id'],
  },
  facility_cancel_listing: {
    usage: '<listing_id>',
    category: 'Facilities',
    apiRoute: 'POST /api/v2/spacemolt_facility/cancel_listing',
    positionals: ['listing_id'],
  },
};
